version: '2'
services:
    resalab-app:
        image: resalab
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://resalab-mysql:3306/resalab?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    resalab-mysql:
        extends:
            file: mysql.yml
            service: resalab-mysql
